version: '3'
services:
    node:
        restart: always
        build: .
        ports:
            - 3000:3000
        volumes:
            - ./:/code
    mongo:
        image: mongo:3.0
        ports:
        - 27017:27017
        volumes:
        - mongodb:/data/db
volumes:
    mongodb:
